BBBB BBBBBBBBBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
	XXXXXXXXXXX XXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX	
XXXXXXX
XXXXXX
	BBBBBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
		XXXX  XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XX
		XXXXX
			XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXX XXX XXXXXXXXXXXXXXX XXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
			XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
			  BBBBBBBBBB

			  BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
			    
			  BBBBBB

			  BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
			    XXXX XXXXXXXXXXXXXXXXXXX
			      
			      BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB
			      BB BBBBBBBBBBBBBBB
			        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
			      BBBBB
			    XXXXXX
			  BBBBBB

			  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXX
			XXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
	XXXXXX
XXXXXX

BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXXX