
BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBBBBBB BBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
			XXXX  XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
				XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
			XXXXX
            XX XXXXXXBBB BBBBBBXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXX
            XXXX
		XXXXXX
	XXXXXX
	XXXXX
	BBB BBBB BB BBBBBBBBB
		XXXX XXXXXXXXXXXX 
			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX 
			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXX
					
			    XXX XXXXXXXXXXXXXXXXXXXXXX XX
					XX XXXXXXBBB BBBBBBBB BBBBBBBXXXXXX  XXXXX XXXXXXXXXXXXXXXXXXXXX
				XXXXX	
			  XXXXX
				XXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
				XX XXXXXXBBB BBBBBBBB BBBBBBBXX
					XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
						XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXX
				XXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBB BBBBBBBXX
					XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
						XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXX
				XXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBBBB BBBBBBBXX
					XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
						XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXX
				XXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
		XXXXXX
	BBBBBB
XXXXXX
BBBBBBBB
BBBBBBBBBBB